# Spatial Accessibility of Global Fund Clincs in Nigeria

## Required Packages

In [2]:
import geopandas as gpd
import pandas as pd
import requests

## Datasets

Population Density Dataset: https://data.humdata.org/dataset/highresolutionpopulationdensitymaps-nga

Global Fund Clinic Data : Global Fund 

Nigeria Administrative Boundaries: https://data.humdata.org/dataset/cod-ab-nga

## PreProcessing

### Admin Boundaries

Extract geojson and convert to geopandas

In [3]:
nigeria_admin_boundaries_gpd = gpd.read_file("Datasets/nga_admin_boundaries.geojson/nga_admin1.geojson")
nigeria_admin_boundaries_gpd.head()

,adm1_name,adm1_name1,adm1_name2,adm1_name3,adm1_pcode,adm0_name,adm0_name1,adm0_name2,adm0_name3,adm0_pcode,...,area_sqkm,version,lang,lang1,lang2,lang3,adm1_ref_name,center_lat,center_lon,geometry
0,Abia,None,None,None,NG001,Nigeria,None,None,None,NG,...,4859.503138,v01,en,None,None,None,Abia,5.431820,7.488342,"POLYGON ((7.38681 6.03667, 7.38479 6.03732, 7...."
1,Adamawa,None,None,None,NG002,Nigeria,None,None,None,NG,...,37821.673841,v01,en,None,None,None,Adamawa,9.162647,12.291562,"POLYGON ((13.62129 10.94823, 13.61444 10.94922..."
2,Akwa Ibom,None,None,None,NG003,Nigeria,None,None,None,NG,...,6739.355992,v01,en,None,None,None,Akwa Ibom,4.990470,7.795569,"MULTIPOLYGON (((7.71063 5.51935, 7.70777 5.518..."
3,Anambra,None,None,None,NG004,Nigeria,None,None,None,NG,...,4805.519482,v01,en,None,None,None,Anambra,6.248529,6.937873,"POLYGON ((6.93254 6.7109, 6.93298 6.72266, 6.9..."
4,Bauchi,None,None,None,NG005,Nigeria,None,None,None,NG,...,48516.713332,v01,en,None,None,None,Bauchi,10.997894,9.325817,"POLYGON ((10.75125 12.46148, 10.74211 12.46538..."

### Global Fund Clincs

Extracting the clincs from the CSV and into a geopandas dataframe

In [4]:
# Read in the excel to a dataframe
global_fund_clinics_pd = pd.read_excel("Datasets/LMD Input Data.xlsx",sheet_name='HL')
global_fund_clinics_pd.head()

,Origin,Origin Latitude,Origin Longitude,Origin State,Origin LGA,Destination,Destination Latitude,Destination Longitude,Destination State,Destination LGA,Destination STATE__LGA,Distance,Duration,Distance (km),Duration (min),Straight Line Distance,Circuity Factor
0,Uyo Hub,5.0377,7.9128,Akwa Ibom,Uyo,"Aba South,ABIA",5.107629,7.379234,ABIA,Aba South,ABIA__Aba South,69139.80,3090.31,69.13980,51.505167,59.668366,1.158735
1,Uyo Hub,5.0377,7.9128,Akwa Ibom,Uyo,"Abaji,FCT",8.486525,6.944094,FCT,Abaji,FCT__Abaji,583713.88,27816.06,583.71388,463.601000,396.150279,1.473466
2,Uyo Hub,5.0377,7.9128,Akwa Ibom,Uyo,"Abak,AKWA IBOM",4.986572,7.791783,AKWA IBOM,Abak,AKWA IBOM__Abak,18254.51,868.84,18.25451,14.480667,14.562721,1.253510
3,Uyo Hub,5.0377,7.9128,Akwa Ibom,Uyo,"Abakaliki,EBONYI",6.210362,8.112093,EBONYI,Abakaliki,EBONYI__Abakaliki,218948.34,10196.21,218.94834,169.936833,131.544913,1.664438
4,Uyo Hub,5.0377,7.9128,Akwa Ibom,Uyo,"Abeokuta North,OGUN",7.167720,3.320590,OGUN,Abeokuta North,OGUN__Abeokuta North,659942.94,28233.16,659.94294,470.552667,560.220283,1.178006

In [5]:
# Convert to geopandas dataframe
global_fund_clincs_gpd = gpd.GeoDataFrame(global_fund_clinics_pd, 
    geometry = gpd.points_from_xy(global_fund_clinics_pd['Destination Longitude'], global_fund_clinics_pd['Destination Latitude']), 
    crs = 'EPSG:4326')

In [5]:
#V alidate that the clinics are admin boundaries are correct visually
folium_map = nigeria_admin_boundaries_gpd.explore()
global_fund_clincs_gpd.explore(m=folium_map, color='red', marker_kwds={'radius':1, 'fill':True})   
folium_map

NameError: name 'nigeria_admin_boundaries_gpd' is not defined

### Population Density

Want to process the raster